### ISSUE TITLE
Deal with errors on Queue.html page

### ISSUE THREAD

**Issue by TheoBr** [TheoBr/QRL#12]
You can see the errors by:
1. Open Queue.html through extension (Add To Queue)
2. Right click on page
3. Click "inspect element"
4. Click "Console"
5. See the horrors I'm dealing with

**Comment by amanz360** [comment]
I just downloaded it and tried it out, no errors come up in my console and the media loads. Looks like it's working here, what does it say for you?

**Comment by TheoBr** [comment]
Mole's solution addresses all of these
