### ISSUE TITLE
Store queueTabId and queueTabOpen

### ISSUE THREAD

**Issue by TheoBr** [TheoBr/QRL#13]
**edit** Store them in Chrome Sync **/edit**

If we made sure queueTabId was null when the queue tab was closed, we wouldn't even need queueTabOpen

**Comment by amanz360** [comment]
I'm not quite sure what you mean when you ask to store them in chrome sync. The tab id changes every time the tab is opened and closed so there's no point in saving an id in between browser sessions because it will be different the next time the user uses the program. I did make the change though.
