### ISSUE TITLE
Make a thisTabId variable set to the ID of the tab the JS is running in

### ISSUE THREAD

**Issue by TheoBr** [TheoBr/QRL#14]

**Comment by amanz360** [comment]
I'm also not sure what you want here. queueTabId stores the id of the tab that opens when you add something to the queue. This is the Queue.html file which is where the js is running. So you already have access to the this id at all times while it exists, so could you clarify what it is you're looking for?

**Comment by TheoBr** [comment]
We don't need this with the current implementation
