### ISSUE TITLE
Handle "restricted" videos

### ISSUE THREAD

**Issue by TheoBr** [TheoBr/QRL#16]
If a copywritten video gets added, there's no way to get around it

**Comment by TheoBr** [comment]
Also, Streamus plays them somehow, similar plugin that's open source.

https://github.com/MeoMix/StreamusChromeExtension

**Comment by amanz360** [comment]
Yeah, I forgot to mention that. The only way to get around it is you have to reset by clearing the storage and reloading the extension.

**Comment by TheoBr** [comment]
I'm sure it throws some form of state. Play with the onStateChange function in the queuePage.js , I bet you'll figure it out in no time

**Comment by TheoBr** [comment]
The "skip" button works for now, but I would like a better solution in the future
