### ISSUE TITLE
[BUG] [MAJOR] Fix VideoID Parsing For Long URLs

### ISSUE THREAD

**Issue by TheoBr** [TheoBr/QRL#19]
I.e. https://www.youtube.com/watch?v=m4-9mYrbXVI&index=1&list=PLSOaquWL60FvwZXWBIG6D86B1eoKg3WNb

I thought this was handled but I guess not and idk how that wizardry works

**Comment by emmetthitz** [comment]
This will be handled with parsing redirects as well.
