### ISSUE TITLE
[BUG] [MINOR] Queue doesn't load the first time it's opened

### ISSUE THREAD

**Issue by emmetthitz** [TheoBr/QRL#28]
Steps to recreate:

Close chrome completely
Attempt to add content to queue
Doesn't load in queue page
Attempt to add content to queue again
Success

**Comment by emmetthitz** [comment]
I lied, this only seems to happen the first time the extension is loaded.

**Comment by barbam** [comment]
I also notice that if the queue tab is not open, if you try to add content, it will open the queue tab but not add it. I'm not sure if this is related..

**Comment by amanz360** [comment]
One never steps in the same stream twice.
