### ISSUE TITLE
[BUG] [MAJOR] Queue occasionally fails to load subsequent content

### ISSUE THREAD

**Issue by emmetthitz** [TheoBr/QRL#29]
Trying to figure out recreation steps

**Comment by emmetthitz** [comment]
This happens consistently if the queue page isn't the active tab

**Comment by barbam** [comment]
Yes, I noticed this too, if the queue tab is not open, the video is not added (or doesn't show up).

**Comment by emmetthitz** [comment]
Steps to recreate:

Add 2+ content elements to queue
Change tab to anything that isn't the queue page
Wait for content to finish playing
Change tab back to queue page
Video is finished, but not removed from queue, and does not automatically play the next queued element

**Comment by TheoBr** [comment]
Yeah don't think this is real

**Comment by emmetthitz** [comment]
Reproducible with 100% success rate

**Comment by amanz360** [comment]
I had 100% success rate reproducing with your mom
