### ISSUE TITLE
Set up "Automatic Releases" for every other Sunday at midnight

### ISSUE THREAD

**Issue by TheoBr** [TheoBr/QRL#7]
I've been googling and it seems obnoxious. Someone else should handle this one?

**Comment by amanz360** [comment]
So it looks like to truly have automatic releases, you'd have to write your own script that would push a release using shell commands. How long does it take to manually do a release? I could see this working best on a dedicated linux machine which I don't have, it may be less effort to just manually do the releases.

**Comment by barbam** [comment]
I can't seem to find any easy way to do this. The only thing that could be
potentially relevant is this
https://developer.chrome.com/extensions/autoupdate if we add the
 update_url field to manifest.json and could possibly edit the extensions
update frequency?

**Comment by TheoBr** [comment]
It would be git or github specific, I'll make my Raspberry Pi do it. Making a manual release now!
