### ISSUE TITLE
Make HTML page open with "Add To Queue" action

### ISSUE THREAD

**Issue by TheoBr** [TheoBr/QRL#9]
Also make sure the video ID is passed, or that it accesses the queue to fetch the video ID

**Comment by amanz360** [comment]
Well the page opens now but the youtube player doesn't work, so we have to figure out exactly how we can get that HTML page to deliver content and do it well.

**Comment by barbam** [comment]
I think there also needs to be a check if there is already a queue tab open, and if so it doesn't need to open another.

**Comment by barbam** [comment]
https://developer.chrome.com/extensions/tabs#event-onRemoved
See the onRemoved listener for when a tab closes

**Comment by barbam** [comment]
Okay I think I got it working correctly. I committed but you guys should probably check it.

**Comment by amanz360** [comment]
I've downloaded it and tried it out, it seems to be working just fine. The code looks good as well so I'd say this is done.
